var homepage = "homepage";
var login = "login";
var register = "register";
var forgotPassword = "forgotPassword";
var dm = "dm";
var about = "about";
var contactUs = "contactUs";
var profile = "profile";
var blockedUsers = "blocked_users";
var spotifyLogin = "spotifyLogin"; // redirected in wake api call
var chatLanguages = "chatLanguages";
var profilePicSelection = "profilePicSelection";
var drawYourself = "drawYourself";
