name: build-jam-apk

on: push
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          tag: "latest"
          artifacts: "build/app/outputs/apk/debug/*.apk"
          token: ${{ secrets.REPO_TOKEN_NAME }}